version: "3.9"

########################### SERVICES
services:
  ########################### DAINF LABS API
  dainflabsapi:
    image: dainflabsapi
    container_name: dainflabsapi
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8099
      - DATABASE_URL=jdbc:postgresql://postgresql:5432/dainf_labs
      - DATABASE_USERNAME="${DATABASE_USERNAME}"
      - DATABASE_PASSWORD="${DATABASE_PASSWORD}"
      - GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}"
      - GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET}"
      - UTFPR_SECRET=123456
      - UTFPR_TOKEN_SECRET="${UTFPR_TOKEN_SECRET}"
      - UTFPR_EMAIL_ADDRESS="${UTFPR_EMAIL_ADDRESS}"
      - UTFPR_EMAIL_PASSWORD="${UTFPR_EMAIL_PASSWORD}"
    ports:
      - "8099:8099"
    labels:
        # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.dainflabsapi.rule=Host(`app.pb.utfpr.edu.br`) && PathPrefix(`/dainf-labs-api`)"
      - "traefik.http.services.dainflabsapi.loadbalancer.server.port=8099"

      #middlewares
      #- "traefik.http.routers.dainflabsapi.middlewares=dainflabsapi-stripprefix"
      #- "traefik.http.middlewares.dainflabsapi-stripprefix.stripprefix.prefixes=/dainf-labs-api"
      #- "traefik.http.middlewares.dainflabsapi-stripprefix.stripprefix.forceSlash=false"

      #services
      #- "traefik.http.services.dainflabsapi-dainflabsapi.loadbalancer.server.port=80"
    volumes:
      - ./upload:/opt/uploads
    restart: unless-stopped
    networks:
      - web
      - database

########################### NETWORKS
networks:
  web:
    name: web
    driver: bridge
    external: true
    attachable: true
  database:
    name: database
    driver: bridge
    external: false
    attachable: true
      