version: "3.9"

########################### SERVICES
services:
  dainf-labs-api:
    image: dainf-labs-api
    container_name: dainf-labs-api
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8099
      - DATABASE_URL=jdbc:postgresql://postgresql:5432/dainf_labs
      - DATABASE_USERNAME="${DATABASE_USERNAME}"
      - DATABASE_PASSWORD="${DATABASE_PASSWORD}"
      - GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}"
      - GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET}"
      - UTFPR_SECRET=123456
      - UTFPR_TOKEN_SECRET="${UTFPR_TOKEN_SECRET}"
      - UTFPR_EMAIL_ADDRESS="${UTFPR_EMAIL_ADDRESS}"
      - UTFPR_EMAIL_PASSWORD="${UTFPR_EMAIL_PASSWORD}"
    ports:
      - "8099:8099"
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - "traefik.http.routers.dainf-labs-api.rule=Host(`app.pb.utfpr.edu.br`) && PathPrefix(`/dainf-labs-api`)"
      - "traefik.http.routers.dainf-labs-api.entrypoints=websecure"
      - "traefik.http.routers.dainf-labs-api.tls.certresolver=letsencrypt"
    volumes:
      - ./upload:/opt/uploads
    restart: always
    networks:
      - utfpr
      - database

networks:
  utfpr:
    name: utfpr
    driver: bridge
    external: true
    attachable: true
  database:
    name: database
    internal: true
    attachable: true
      