version: "3.9"

########################### SERVICES
services:
  ########################### DAELE LABS API
  daele-labs-api:
    image: daele-labs-api
    container_name: daele-labs-api
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8110
      - DATABASE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - UTFPR_TOKEN_SECRET=${UTFPR_TOKEN_SECRET}
      - UTFPR_EMAIL_ADDRESS=${UTFPR_EMAIL_ADDRESS}
      - UTFPR_EMAIL_PASSWORD=${UTFPR_EMAIL_PASSWORD}
      - UTFPR_EMAIL_USERNAME=${UTFPR_EMAIL_USERNAME}
      - UTFPR_EMAIL_HOST=${UTFPR_EMAIL_HOST}
      - UTFPR_EMAIL_PORT=${UTFPR_EMAIL_PORT}
      - UTFPR_FRONT_URL=${UTFPR_FRONT_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_SECURE=${MINIO_SECURE}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - TZ=America/Sao_Paulo
    ports:
      - "8110:8110"
    labels:
        # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.daele-labs-api.rule=Host(`daele-labs-api.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.daele-labs-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.daele-labs-api.entrypoints=websecure"

    volumes:
      - ./appdata/daele-labs/upload:/opt/uploads
    restart: unless-stopped
    networks:
      - web
      - database

########################### NETWORKS
networks:
  web:
    name: web
    driver: bridge
    external: true
    attachable: true
  database:
    name: database
    driver: bridge
    external: false
    attachable: true
      