version: "3.9"
########################### NETWORK
networks:
  web:
    external: true
  internal:
    external: false

########################### SERVICES
services:
  dainf-labs-api:
    image: dainf-labs-api
    container_name: dainf-labs-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - "traefik.http.routers.dainf-labs-api.rule=Host(`app.pb.utfpr.edu.br`) && PathPrefix(`/dainf-labs-api`)"
      - "traefik.http.routers.dainf-labs-api.entrypoints=websecure"
      - "traefik.http.routers.dainf-labs-api.tls.certresolver=letsencrypt"
    volumes:
      - ./upload:/opt/uploads
    restart: always
    networks:
      - web
      - internal