spring.profiles.active=dev
google.clientId=${env.GOOGLE_CLIENT_ID}
utfpr.secret=${env.UTFPR_SECRET}
utfpr.token.secret=${env.UTFPR_TOKEN_SECRET}
utfpr.email.address=${env.UTFPR_EMAIL_ADDRESS}
utfpr.email.password=${env.UTFPR_EMAIL_PASSWORD}