INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 1');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 2');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 3');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 4');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 5');
