-- INSERT PERMISSAO
INSERT INTO PERMISSAO (NOME) values('ROLE_ADMINISTRADOR');
INSERT INTO PERMISSAO (NOME) values('ROLE_LABORATORISTA');
INSERT INTO PERMISSAO (NOME) values('ROLE_PROFESSOR');
INSERT INTO PERMISSAO (NOME) values('ROLE_ALUNO');

-- INSERT USUARIO (TODOS AS SENHAS SÃO: 123)
-- Nota: email_verificado default é FALSE
INSERT INTO USUARIO (NOME, USERNAME, PASSWORD, EMAIL, DOCUMENTO, TELEFONE, EMAIL_VERIFICADO) VALUES ('Administrador', 'utfprapps-pb', '$2a$10$kcDpG6r2c0karXuOK114Hejk7iguH.tFswB1aenCydA6bmzixjCCC', 'utfprapps-pb@utfpr.edu.br', '000000', '4632202593', TRUE);
INSERT INTO USUARIO (NOME, USERNAME, PASSWORD, EMAIL, DOCUMENTO, TELEFONE, EMAIL_VERIFICADO) VALUES ('Gustavo Arcari', 'gustavoarcari', '$2a$10$kcDpG6r2c0karXuOK114Hejk7iguH.tFswB1aenCydA6bmzixjCCC', 'gustavoarcari@utfpr.edu.br', '000000', '4632202592', TRUE);
INSERT INTO USUARIO (NOME, USERNAME, PASSWORD, EMAIL, DOCUMENTO, TELEFONE, EMAIL_VERIFICADO) VALUES ('Vinicius Pegorini', 'vinicius', '$2a$10$kcDpG6r2c0karXuOK114Hejk7iguH.tFswB1aenCydA6bmzixjCCC', 'vinicius@professores.utfpr.edu.br', '2721471', '46999711050', TRUE);

-- INSERT USUARIOS ADICIONAIS PARA TESTES (do import.sql antigo)
INSERT INTO USUARIO (NOME, USERNAME, PASSWORD, EMAIL, DOCUMENTO, TELEFONE, EMAIL_VERIFICADO) VALUES ('Gustavo Henrique Zaffani', 'gustavo', '$2a$10$kcDpG6r2c0karXuOK114Hejk7iguH.tFswB1aenCydA6bmzixjCCC', 'gzaffani@alunos.utfpr.edu.br', '1234', '46999668855', TRUE);
INSERT INTO USUARIO (NOME, USERNAME, PASSWORD, EMAIL, DOCUMENTO, TELEFONE, EMAIL_VERIFICADO) VALUES ('Thiago Zaffani', 'thiago', '$2a$10$kcDpG6r2c0karXuOK114Hejk7iguH.tFswB1aenCydA6bmzixjCCC', 'thiago@alunos.utfpr.edu.br', '2345', '46999668855', TRUE);
INSERT INTO USUARIO (NOME, USERNAME, PASSWORD, EMAIL, DOCUMENTO, TELEFONE, EMAIL_VERIFICADO) VALUES ('João da Silva', 'joao', '$2a$10$kcDpG6r2c0karXuOK114Hejk7iguH.tFswB1aenCydA6bmzixjCCC', 'joao@alunos.utfpr.edu.br', '4567', '46999668855', TRUE);
INSERT INTO USUARIO (NOME, USERNAME, PASSWORD, EMAIL, DOCUMENTO, TELEFONE, EMAIL_VERIFICADO) VALUES ('Antenor de Souza', 'antenor', '$2a$10$kcDpG6r2c0karXuOK114Hejk7iguH.tFswB1aenCydA6bmzixjCCC', 'antenor@alunos.utfpr.edu.br', '4568', '46999668855', TRUE);
INSERT INTO USUARIO (NOME, USERNAME, PASSWORD, EMAIL, DOCUMENTO, TELEFONE, EMAIL_VERIFICADO) VALUES ('Mainara Lorencena', 'nara', '$2a$10$kcDpG6r2c0karXuOK114Hejk7iguH.tFswB1aenCydA6bmzixjCCC', 'nara@alunos.utfpr.edu.br', '4569', '46999668855', TRUE);
INSERT INTO USUARIO (NOME, USERNAME, PASSWORD, EMAIL, DOCUMENTO, TELEFONE, EMAIL_VERIFICADO) VALUES ('Raul Cardoso', 'raul', '$2a$10$kcDpG6r2c0karXuOK114Hejk7iguH.tFswB1aenCydA6bmzixjCCC', 'raul@alunos.utfpr.edu.br', '4570', '46999668855', TRUE);
INSERT INTO USUARIO (NOME, USERNAME, PASSWORD, EMAIL, DOCUMENTO, TELEFONE, EMAIL_VERIFICADO) VALUES ('Joana de Oliveira', 'joana', '$2a$10$kcDpG6r2c0karXuOK114Hejk7iguH.tFswB1aenCydA6bmzixjCCC', 'joana@alunos.utfpr.edu.br', '4571', '46999668855', TRUE);
INSERT INTO USUARIO (NOME, USERNAME, PASSWORD, EMAIL, DOCUMENTO, TELEFONE, EMAIL_VERIFICADO) VALUES ('Fábio Favarim', 'favarim', '$2a$10$kcDpG6r2c0karXuOK114Hejk7iguH.tFswB1aenCydA6bmzixjCCC', 'favarim@professores.utfpr.edu.br', '3457', '46999668855', TRUE);

-- INSERT PERMISSÕES DOS USUÁRIOS
INSERT INTO USUARIO_PERMISSOES(USUARIO_ID, PERMISSOES_ID) VALUES (1, 1); -- Administrador -> ADMIN
INSERT INTO USUARIO_PERMISSOES(USUARIO_ID, PERMISSOES_ID) VALUES (2, 1); -- Gustavo Arcari -> ADMIN
INSERT INTO USUARIO_PERMISSOES(USUARIO_ID, PERMISSOES_ID) VALUES (3, 1); -- Vinicius -> ADMIN
INSERT INTO USUARIO_PERMISSOES(USUARIO_ID, PERMISSOES_ID) VALUES (4, 4); -- Gustavo Zaffani -> ALUNO
INSERT INTO USUARIO_PERMISSOES(USUARIO_ID, PERMISSOES_ID) VALUES (5, 4); -- Thiago -> ALUNO
INSERT INTO USUARIO_PERMISSOES(USUARIO_ID, PERMISSOES_ID) VALUES (6, 2); -- João -> LABORATORISTA
INSERT INTO USUARIO_PERMISSOES(USUARIO_ID, PERMISSOES_ID) VALUES (7, 2); -- Antenor -> LABORATORISTA
INSERT INTO USUARIO_PERMISSOES(USUARIO_ID, PERMISSOES_ID) VALUES (8, 3); -- Mainara -> PROFESSOR
INSERT INTO USUARIO_PERMISSOES(USUARIO_ID, PERMISSOES_ID) VALUES (9, 4); -- Raul -> ALUNO
INSERT INTO USUARIO_PERMISSOES(USUARIO_ID, PERMISSOES_ID) VALUES (10, 2); -- Joana -> LABORATORISTA
INSERT INTO USUARIO_PERMISSOES(USUARIO_ID, PERMISSOES_ID) VALUES (11, 3); -- Favarim -> PROFESSOR

--INSERT GRUPO
INSERT INTO GRUPO (DESCRICAO) VALUES ('Materiais Permanentes');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Materiais de Consumo');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Periféricos');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Outros');

-- GRUPOS ADICIONAIS PARA TESTES (do import.sql antigo)
INSERT INTO GRUPO (DESCRICAO) VALUES ('Arduinos');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 1');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 2');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 3');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 4');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 5');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 6');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 7');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 8');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 9');
INSERT INTO GRUPO (DESCRICAO) VALUES ('Grupo 10');

-- INSERT FORNECEDOR
INSERT INTO FORNECEDOR (RAZAO_SOCIAL, NOME_FANTASIA, CNPJ, IE, ENDERECO, CIDADE_ID, ESTADO_ID) VALUES ('Fornecedor Padrão', 'Nome Fornecedor Padrão', '75101873000190', '1239987', 'Endereço do Fornecedor Padrão', 1, 2);

--INSERT ITEM
INSERT INTO ITEM (NOME, PATRIMONIO, SIORG, VALOR, QTDE_MINIMA, LOCALIZACAO, TIPO_ITEM, SALDO, GRUPO_ID) VALUES ('(Novo Item)', 0000, 0000, 000.00, 1, 'Não editar esse item!', 'C', 1, 1);

-- INSERT RELATORIO
INSERT INTO RELATORIO (NAME_REPORT, NOME) VALUES ( 'HistoricoEmprestimoUsuario.jrxml', 'Histórico de Empréstimo do Usuário X');
INSERT INTO RELATORIO (NAME_REPORT, NOME) VALUES ( 'ItensSemEstoque.jrxml', 'Itens Sem Saldo no Estoque');
INSERT INTO RELATORIO (NAME_REPORT, NOME) VALUES ( 'EmprestimosRealizadosEntre.jrxml', 'Emprestéstimos Realizados Entre');
INSERT INTO RELATORIO (NAME_REPORT, NOME) VALUES ( 'ReservaDoItem.jrxml', 'Reservas do Item');
INSERT INTO RELATORIO (NAME_REPORT, NOME) VALUES ( 'SolicitacaoItem.jrxml', 'Solicitações de Compra do Item');
INSERT INTO RELATORIO (NAME_REPORT, NOME) VALUES ( 'ItensAtingiramQtdeMinima.jrxml', 'Itens que Atingiram a Quantidade Mínima');

-- INSERT RELATORIO_PARAM
INSERT INTO RELATORIO_PARAMS (ALIAS_PARAM, NAME_PARAM, TIPO_PARAM, RELATORIO_ID) VALUES ( 'RA/ SIAPE', 'DOCUMENTO', 'S', 1);
INSERT INTO RELATORIO_PARAMS (ALIAS_PARAM, NAME_PARAM, TIPO_PARAM, RELATORIO_ID) VALUES ( 'Data Inicial', 'DT_INI', 'D', 3);
INSERT INTO RELATORIO_PARAMS (ALIAS_PARAM, NAME_PARAM, TIPO_PARAM, RELATORIO_ID) VALUES ( 'Data Final', 'DT_FIM', 'D', 3);
INSERT INTO RELATORIO_PARAMS (ALIAS_PARAM, NAME_PARAM, TIPO_PARAM, RELATORIO_ID) VALUES ( 'Cód do Item', 'ID_ITEM', 'N', 4);
INSERT INTO RELATORIO_PARAMS (ALIAS_PARAM, NAME_PARAM, TIPO_PARAM, RELATORIO_ID) VALUES ( 'Cód do Item', 'ID_ITEM', 'N', 5)
