-- Nota: As colunas email_verificado e codigo_verificacao já foram criadas em V1.0__Init.sql para testes
-- Portanto não precisamos ADD COLUMN aqui (já existem no schema inicial de teste)

CREATE TABLE IF NOT EXISTS tb_recover_password (
   id bigint generated by default as identity,
   code varchar(1024) NOT NULL,
   email varchar(255) NOT NULL,
   date_time date NOT NULL,
   primary key (id)
);