CREATE TABLE IF NOT EXISTS system_config (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             nada_consta_email VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT FALSE
    );


-- Insere uma linha padrão ativa, se necessário
INSERT INTO system_config (id, nada_consta_email, is_active)
SELECT 1, 'default@utfpr.edu.br', TRUE
    WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE is_active = TRUE);
