ALTER TABLE usuario ADD COLUMN email_verificado bool;
ALTER TABLE usuario ADD COLUMN codigo_verificacao varchar(512);

CREATE TABLE IF NOT EXISTS tb_recover_password (
   id bigint generated by default as identity,
   code varchar(1024) NOT NULL,
   email varchar(255) NOT NULL,
   date_time date NOT NULL,
   primary key (id)
);